create table tb_boleto (
   id bigint generated by default as identity,
    customer varchar(255),
    due_date date not null,
    status varchar(255) not null,
    total_in_cents decimal(19,2) not null,
    primary key (id)
);

INSERT INTO tb_boleto (due_date, total_in_cents, customer, status)
VALUES
('2018-01-01', 100000, 'Trillian Company', 'PENDING');